name: ${DOCKER_PROJECT_NAME:-AppName}

services:
  api:
    profiles: 
      - ${DOCKER_COMPOSE_PROFILE:-App}
      - ${API_COMPOSE_PROFILE:-Api}
    container_name: ${API_CONTAINER_NAME:-Api}
    image: ${API_IMAGE_NAME:-ApiName}:${API_IMAGE_TAG:-latest}
    pull_policy: ${API_IMAGE_PULL_POLICY:-if_not_present}
    restart: unless-stopped
    ports:
      - "${API_HTTP_PORT:-5095}:${API_CONTAINER_HTTP_PORT:-8080}"
      - "${API_HTTPS_PORT:-5096}:${API_CONTAINER_HTTPS_PORT:-8443}"
    env_file:
      - .env
    build:
      context: ..
      dockerfile: App/Dockerfile
    #volumes:
    #  - ./certs:/https:ro
    depends_on:
      mysql: 
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ${DOCKER_COMPOSE_NETWORK:-AppNetwork}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${API_CONTAINER_HTTP_PORT:-8080}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    
      
  mysql:
    profiles: 
      - ${DOCKER_COMPOSE_PROFILE:-App}
      - ${MYSQL_COMPOSE_PROFILE:-Database}
    container_name: ${MYSQL_CONTAINER_NAME:-MySQL}
    image: ${MYSQL_IMAGE_NAME:-mysql}:${MYSQL_IMAGE_TAG:-8.4}
    pull_policy: ${MYSQL_IMAGE_PULL_POLICY:-if_not_present}
    restart: unless-stopped
    #expose: // Staging and Production
    #  - "${MYSQL_EXPOSE_PORT:-3308}"
    ports:
      - "${MYSQL_HTTP_PORT:-3308}:${MYSQL_CONTAINER_HTTP_PORT:-3306}"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - ${DOCKER_COMPOSE_NETWORK:-AppNetwork}
  
  redis:
    profiles:
      - ${DOCKER_COMPOSE_PROFILE:-App}
      - ${REDIS_COMPOSE_PROFILE:-Cache}
    container_name: ${REDIS_CONTAINER_NAME:-Redis}
    image: ${REDIS_IMAGE_NAME:-redis}:${REDIS_IMAGE_TAG:-latest}
    pull_policy: ${REDIS_IMAGE_PULL_POLICY:-if_not_present}
    restart: unless-stopped
    #expose: // Staging and Production
    #  - "${REDIS_EXPOSE_PORT:-6380}"
    ports:
      - "${REDIS_HTTP_PORT:-6380}:${REDIS_CONTAINER_HTTP_PORT:-6379}"
    env_file:
      - .env
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - ${DOCKER_COMPOSE_NETWORK:-AppNetwork}
    
  aspire-dashboard:
    profiles:
      - ${DOCKER_COMPOSE_PROFILE:-App}
      - ${ASPIRE_COMPOSE_PROFILE:-Dashboard}
    container_name: ${ASPIRE_CONTAINER_NAME:-AspireDashboard}
    image: ${ASPIRE_IMAGE_NAME:-mcr.microsoft.com/dotnet/nightly/aspire-dashboard}:${ASPIRE_IMAGE_TAG:-latest}
    pull_policy: ${ASPIRE_IMAGE_PULL_POLICY:-if_not_present}
    restart: unless-stopped
    ports:
      - "${ASPIRE_HTTP_PORT:-18888}:${ASPIRE_CONTAINER_HTTP_PORT:-18888}"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:18888/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ${DOCKER_COMPOSE_NETWORK:-AppNetwork}
    
  rabbitmq:
    profiles:
      - ${DOCKER_COMPOSE_PROFILE:-App}
      - ${RABBITMQ_COMPOSE_PROFILE:-Message}
    container_name: ${RABBITMQ_CONTAINER_NAME:-RabbitMQ}
    image: ${RABBITMQ_IMAGE_NAME:-rabbitmq}:${RABBITMQ_IMAGE_TAG:-latest}
    pull_policy: ${RABBITMQ_IMAGE_PULL_POLICY:-if_not_present}
    restart: unless-stopped
    #expose: // Staging and Production
    #  - "${RABBITMQ_EXPOSE_PORT:-5673}"
    ports:
      - "${RABBITMQ_HTTP_PORT:-5673}:${RABBITMQ_CONTAINER_HTTP_PORT:-5672}"
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5   
    networks:
      - ${DOCKER_COMPOSE_NETWORK:-AppNetwork}
  
networks:
  ${DOCKER_COMPOSE_NETWORK}:
    driver: bridge


